

    catch(int x)
    {
        cout<<"Can't divide by: "<<x<<endl;
    }
    

 return 0;